function checkexists(filepath)
    % Check that a file exists at filepath
    if ~isfile(filepath)
        error('OpenMRF:FileNotFoundError', ...
              'Required file file at ''%s'' does not exist!', ...
              filepath);
    elseif isfolder(filepath)
        error('OpenMRF:IsADirectoryError', ...
              'Expected a file but found a directory at ''%s''', ...
              filepath);
    end 
end